@baseURL = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create-account
POST {{baseURL}}/accounts
Content-Type: application/json

{
  "name": "Rafael",
  "email": "rafaelcamara2@rocketseat.com.br",
  "password": "123456"
}

###

# @name authenticate
POST {{baseURL}}/sessions
Content-Type: application/json

{
  "email": "rafaelcamara2@rocketseat.com.br",
  "password": "123456"
}

###

# @name create_question
POST {{baseURL}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}
